.local/bin/backup

diff --git a/.local/bin/backup b/.local/bin/backup
--- a/.local/bin/backup
+++ b/.local/bin/backup
@@ -2,37 +2,30 @@
 
 destination="$2"
 
-GON_BASIC_BACKUP=(
+GON_BACKUP_DIRS=(
+    "--exclude=$HOME/Dropbox/Media_Library/"
     "$HOME/Desktop"
     "$HOME/Downloads"
+    "$HOME/Dropbox"
     "$HOME/.mozilla"
     "$HOME/.ssh"
     "$HOME/.cert"
     "$HOME/.var/app/org.remmina.Remmina/data/remmina"
     "$HOME/.var/app/org.remmina.Remmina/config/remmina"
     "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird"
-    "$HOME/Dropbox/Documents"
-    "$HOME/Dropbox/Games"
-    "$HOME/Dropbox/Pictures"
-    "$HOME/Dropbox/Projects"
-    "$HOME/Dropbox/Programs"
-    "$HOME/Dropbox/Videos"
 )
 
-GON_EXTRA=(
-    "$HOME/Dropbox/Backup"
-    "$HOME/Dropbox/Music"
-)
-
-WORK_SETTINGS=(
+WORK_SETTINGS_DIRS=(
     "$HOME/.local/MATLAB"
     "$HOME/.local/stata14"
     "$HOME/.local/stata-png-fix"
-    # "$HOME/.stata14"
-    # "$HOME/.matlab"
 )
 
-GON_FULL_BACKUP=("${GON_BASIC_BACKUP[@]}" "${GON_EXTRA[@]}" "${WORK_SETTINGS[@]}")
+SMALL_EXCLUDE_DIRS=(
+    "--exclude=$HOME/Dropbox/Backup"
+    "--exclude=$HOME/Dropbox/Music"
+    "--exclude=$HOME/Downloads"
+)
 
 list_mountpoints() {
     lsblk -no MOUNTPOINTS
@@ -52,7 +45,6 @@ get_mountpoint() {
         ((n++))
     done
     read -rep "Enter drive's number: " number
-
     while [[ $(("$number" - 1)) -ge "${#mountpoints[@]}" ]] || [ -z "$number" ]; do
         echo "Number '$number' is not an available option." >&1 1>&2
         unset number
@@ -62,25 +54,12 @@ get_mountpoint() {
     echo "${mountpoints[$(("$number" - 1))]}"
 }
 
-# ask_delete() {
-
-#     prompt=$(
-# 		cat <<-EOF
-# 		Backup interrupted.
-# 		Would you like to delete $backup_dir ? [y/N]:
-# 		EOF
-#     )
-
-#     read -rep "$prompt" reply
-#     if [[ $reply =~ ^[Yy]$ ]]; then
-#         sudo rm -rf "$backup_dir"
-#     fi
-# }
-
 filesystem_check() {
     # 'local' must be used
     local source_dir="$1"
     local destination="$2"
+
+    [[ $source_dir == --exclude=* ]] && return
 
     # TODO: Check if destination exists before using dirname?
     local destination=$(dirname "$destination")
@@ -88,7 +67,8 @@ filesystem_check() {
     # If the destination is "/mnt/drive" the use of "dirname" fails.
 
     if df -P -- "$destination" "$source_dir" | awk 'NR==2 {dev1=$1} NR==3 {exit($1!=dev1)}'; then
-        echo "$destination and $source_dir are on the same filesystem"
+        echo "'$destination' and '$source_dir' are on the same filesystem"
+        echo "More directories may also have this issue."
         # rmdir "$source_dir" 2>/dev/null || echo "$source_dir is not empty."
         exit 1
     fi
@@ -108,42 +88,80 @@ convertsecs() {
 }
 
 dconf_dump() {
-    dconf dump / | sudo tee $1/dconf_FULL.ini > /dev/null
-    [[ `command -v dump_dconf_extension_settings` ]] && dump_dconf_extension_settings &&
+    dconf dump / | sudo tee $1/dconf_FULL.ini >/dev/null
+    [[ $(command -v dump_dconf_extension_settings) ]] && dump_dconf_extension_settings &&
         _rsync "$HOME/.config/dconf" "$1"
 
 }
 
-gon_backup() {
+get_data_sources() {
 
-    local start_="$(date -u +%s)"
-    local start_time=$(date +%F-%T)
-    local destination="$2"
+    case $(hostname) in
+    gon | p14s)
+        # Continue
+        ;;
+    *)
+        printf "Hostname '%s' not found. Nothing was/will be backed up\n\n" $(hostname)
+        exit 1
+        ;;
+    esac
 
     local size="$1"
     case "$size" in
     small)
-        data_sources_list=("${GON_BASIC_BACKUP[@]}")
+        data_sources_list=("${SMALL_EXCLUDE_DIRS[@]}" "${GON_BACKUP_DIRS[@]}")
         ;;
 
     big | full)
-        data_sources_list=("${GON_FULL_BACKUP[@]}")
+        data_sources_list=("${GON_BACKUP_DIRS[@]}" "${WORK_SETTINGS_DIRS[@]}")
         ;;
 
     *)
-        printf "Available arguments small|big|full "
-        printf "Nothing was/will be backed up\n\n"
-        exit
+        exit 1
         ;;
     esac
 
-    for dir in "${data_sources_list[@]}"; do
+    echo "${data_sources_list[@]}"
+}
+
+main() {
+    [ -z $destination ] && destination="$(get_mountpoint)"
+
+    destination="$destination/backups"
+
+    data_sources_list=$(get_data_sources $1)
+
+    # Check the exit status of the get_data_sources
+    if [ $? -ne 0 ]; then
+        printf "Available arguments small|big|full\n" &&
+            printf "Nothing was/will be backed up\n\n" &&
+            exit 1
+    fi
+
+    for dir in $data_sources_list; do
         filesystem_check "$dir" "$destination"
     done
 
+    printf "Backup '%s' to '%s' with the following argument? '%s'\n" $(hostname) $destination "$1"
+    printf "The following directories are going to be backed up:"
+    echo " $data_sources_list" | sed 's/ /"\n- "/g' | sed 's/^"//'
+    read -r
+
+    mkdir -p $destination || exit 1
+
+    local start_="$(date -u +%s)"
+    local start_time=$(date +%F-%T)
+    local destination="$destination/$(hostname)_backup"
+
     printf "%s\nStarting backup to: %s\n\n" "$start_time" "$destination"
-    sudo rsync -aAXH --relative -h --info=progress2 --prune-empty-dirs ${data_sources_list[@]} "$destination" &&
-        dconf_dump $destination &&
+    sudo rsync \
+        -aAXH \
+        --relative \
+        -h \
+        --info=progress2 \
+        --prune-empty-dirs \
+        $data_sources_list "$destination" # &&
+    dconf_dump $destination &&
         sudo btrfs subvolume snapshot "$destination" "${destination}_$start_time" &&
         echo "Snapshot created"
 
@@ -151,36 +169,4 @@ gon_backup() {
     convertsecs $((end_ - start_))
 }
 
-# if destination not in mountpoints ask again.
-main() {
-    [ -z $destination ] && destination="$(get_mountpoint)"
-
-    destination="$destination/backups"
-
-    printf "Backing up '%s' to '%s' with the following argument:\n'%s'" $(hostname) $destination "$1"
-    read -r
-
-    mkdir -p $destination
-
-    case $(hostname) in
-    gon | p14s)
-        gon_backup "$1" "$destination/$(hostname)_backup"
-        ;;
-    *)
-        printf "Nothing was/will be backed up\n\n"
-        ;;
-    esac
-
-    # tar \
-    # --directory="$HOME/.var/app/org.mozilla.Thunderbird/" \
-    # -acf \
-    # "${destination}/thunderbird-$(hostname)-$(date +%F).tar.zst" \
-    # .thunderbird
-
-}
-
-# INTERRUPTED='False'
-
 main "$1" "$2"
-
-# trap 'ask_delete; exit 2' INT TERM
