Refactor

diff --git a/.local/bin/btoggle b/.local/bin/btoggle
--- a/.local/bin/btoggle
+++ b/.local/bin/btoggle
@@ -4,46 +4,70 @@
 # Accepts only one device's mac address at a time.
 
 notify() {
-  notify-send "$(basename "$0")" "$@"
+	notify-send --hint=int:transient:1 "$(basename "$0")" "$@"
 }
 
-device="$1"
+is_mac_address() {
+	[[ "$1" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]]
+}
 
-if [ $# -eq 0 ]; then
-    device="headset"
-fi
+get_mac_address() {
+	device="$1"
 
-# Used to create aliases and make it easier to use it from the command line
-case $device in
+	if [ "$device" = "" ]; then
+		device="headset"
+	fi
 
-  earbuds)
-    # honor earbuds
-    MAC_ADDRESS="E0:9D:FA:C8:22:78"
-    ;;
+	# Used to create aliases and make it easier to use it from the command line
+	case $device in
+	earbuds)
+		# honor earbuds
+		echo "E0:9D:FA:C8:22:78"
+		return
+		;;
 
-  headset)
-    # wh1000mx5
-    MAC_ADDRESS="88:C9:E8:30:3B:4F"
-    ;;
+	headset)
+		# wh1000mx5
+		echo "88:C9:E8:30:3B:4F"
+		return
+		;;
 
-  *)
-    MAC_ADDRESS="$device"
-    ;;
-esac
+	*)
+		echo "$device"
+		return
+		;;
+	esac
+}
 
-[[ "$MAC_ADDRESS" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]] ||
-echo "Given MAC_ADDRESS: '${MAC_ADDRESS}' is invalid."
+get_device_name() {
+	bluetoothctl info $mac_address | grep "Name:" | awk -F: '{print $2}'
+}
 
-coproc bluetoothctl
-echo -e 'info ${MAC_ADDRESS}\nexit' >&${COPROC[1]}
-output=$(cat <&${COPROC[0]})
+main() {
 
-dev_status="$(grep ${MAC_ADDRESS} -A9 <<< $output)"
+	mac_address=$(get_mac_address "$1")
+	echo $mac_address
 
-if (grep "Connected: yes" <<< "$dev_status") ; then
-    notify "Attempting to disconnect device: '${device}'"
-    bluetoothctl -- disconnect ${MAC_ADDRESS}
-else
-    notify "Attempting to connect device: '${device}'"
-    bluetoothctl -- connect ${MAC_ADDRESS}
-fi
+	is_mac_address "$mac_address" || echo "Given mac address: '${mac_address}' is invalid."
+
+	# coproc bluetoothctl
+	# echo -e 'info ${mac_address}\nexit' >&${COPROC[1]}
+	# output=$(cat <&${COPROC[0]})
+
+	output=$(bluetoothctl info $mac_address)
+
+	dev_status="$(grep ${mac_address} -A9 <<< $output)"
+
+	device=$(get_device_name)
+
+	if (grep "Connected: yes" <<< "$dev_status") ; then
+		notify "Attempting to disconnect device: '${device}'"
+		bluetoothctl -- disconnect ${mac_address}
+	else
+		notify "Attempting to connect device: '${device}'"
+		bluetoothctl -- connect ${mac_address}
+	fi
+}
+
+
+main $@
