fix(bin): harden utility scripts

diff --git a/.local/bin/btoggle b/.local/bin/btoggle
--- a/.local/bin/btoggle
+++ b/.local/bin/btoggle
@@ -40,7 +40,7 @@ get_mac_address() {
 }
 
 get_device_name() {
-	bluetoothctl info $mac_address | grep "Name:" | awk -F: '{print $2}'
+	bluetoothctl info "$mac_address" | grep "Name:" | awk -F: '{print $2}'
 }
 
 get_power_status(){
@@ -50,18 +50,25 @@ get_power_status(){
 
 main() {
 
-	mac_address=$(get_mac_address "$1")
-	echo $mac_address
+	local mac_address
+	local output
+	local dev_status
+	local device
+	mac_address=$(get_mac_address "${1:-}")
+	printf '%s\n' "$mac_address"
 
-	is_mac_address "$mac_address" || echo "Given mac address: '${mac_address}' is invalid."
+	if ! is_mac_address "$mac_address"; then
+		printf "Given MAC address '%s' is invalid.\n" "$mac_address" >&2
+		return 2
+	fi
 
 	# coproc bluetoothctl
 	# echo -e 'info ${mac_address}\nexit' >&${COPROC[1]}
 	# output=$(cat <&${COPROC[0]})
 
-	output=$(bluetoothctl info $mac_address)
+	output=$(bluetoothctl info "$mac_address")
 
-	dev_status="$(grep ${mac_address} -A9 <<< $output)"
+	dev_status="$(grep -F -A9 -- "$mac_address" <<< "$output")"
 
 	device=$(get_device_name)
 
@@ -73,7 +80,7 @@ main() {
 		[[ $(bluetoothctl devices Connected | wc -l) == 1 ]] &&
 			bluetoothctl power off
 
-		bluetoothctl -- disconnect ${mac_address}
+		bluetoothctl -- disconnect "$mac_address"
 	else
 		notify "Attempting to connect device: '${device}'"
 		# _connect $mac_address
@@ -81,12 +88,12 @@ main() {
 			notify "Turning on Bluethooth adapter...."
 			rfkill unblock all || notify "'rfkill unblock all' failed."
 			bluetoothctl power on; sleep 1; }
-		bluetoothctl -- connect ${mac_address}
+		bluetoothctl -- connect "$mac_address"
 	fi
 }
 
 
-main $@
+main "$@"
 
 # The following need rework:
 
diff --git a/.local/bin/extr b/.local/bin/extr
--- a/.local/bin/extr
+++ b/.local/bin/extr
@@ -4,24 +4,42 @@
 # Default behavior: Extract archive into new directory
 # Behavior with `-c` option: Extract contents into current directory
 
-while getopts "hc" o; do case "${o}" in
-    c) extracthere="True" ;;
-    *) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
-esac done
+usage() {
+    printf 'Usage: %s [-c] ARCHIVE\n' "$(basename "$0")"
+    printf '  -c  Extract into the current directory.\n'
+    printf '  -h, --help  Show this help.\n'
+}
 
-if [ -z "$extracthere" ]; then
-    archive="$(readlink -f "$*")" &&
-    directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
-    mkdir -p "$directory" &&
-    cd "$directory" || exit
-else
-    archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)")"
+extract_here=false
+while [ "$#" -gt 0 ]; do
+    case "$1" in
+        -c) extract_here=true; shift ;;
+        -h | --help) usage; exit 0 ;;
+        --) shift; break ;;
+        -*) usage >&2; exit 2 ;;
+        *) break ;;
+    esac
+done
+
+if [ "$#" -ne 1 ]; then
+    usage >&2
+    exit 2
 fi
 
-[ "$archive" = "" ] && printf "Give archive to extract as argument.\\n" && exit
+archive="$(readlink -f -- "$1")" || exit 1
 
-if [ -f "$archive" ] ; then
-    case "$archive" in
+if [ ! -f "$archive" ]; then
+    printf 'File "%s" not found.\n' "$archive" >&2
+    exit 1
+fi
+
+if ! "$extract_here"; then
+    directory="$(printf '%s\n' "$archive" | sed 's/\.[^\/.]*$//')"
+    mkdir -p -- "$directory" || exit
+    cd -- "$directory" || exit
+fi
+
+case "$archive" in
         *.tar.bz2|*.tar.xz|*.tbz2) tar xvjf "$archive" ;;
         *.tar.gz|*.tgz) tar xvzf "$archive" ;;
         *.lzma) unlzma "$archive" ;;
@@ -35,7 +53,4 @@ if [ -f "$archive" ] ; then
         *.xz) unxz "$archive" ;;
         *.exe) cabextract "$archive" ;;
         *) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
-    esac
-else
-    printf "File \"%s\" not found.\\n" "$archive"
-fi
+esac
