Update dconf syncing script and settings

diff --git a/.local/bin/dconf_sync b/.local/bin/dconf_sync
--- a/.local/bin/dconf_sync
+++ b/.local/bin/dconf_sync
@@ -4,80 +4,103 @@ set -e
 
 # Check if XDG_CONFIG_HOME is set, otherwise use the default $HOME/.config
 if [ -n "$XDG_CONFIG_HOME" ]; then
-  config_dir="$XDG_CONFIG_HOME/dconf"
+    config_dir="$XDG_CONFIG_HOME/dconf"
 else
-  config_dir="$HOME/.config/dconf"
+    config_dir="$HOME/.config/dconf"
 fi
 
 extensions_dir="$config_dir/dconf.d/extensions"
 
-# Function to export extension settings
-export_extension_settings() {
-    dconf dump "/org/gnome/shell/extensions/$1/" >"$extensions_dir/$1"
-}
-
 # Function to load settings
 load_settings() {
     gsettings reset org.gnome.desktop.lockdown disable-lock-screen
-
+    
     path="$config_dir/dconf.ini"
-
+    
     [[ -f "$path" ]] || {
         echo "File: '$path' does not exist"
         exit 1
     }
-
+    
     [[ $(command -v dconf) ]] || {
         echo "dconf is missing or is not in the PATH."
         exit 1
     }
-
+    
     dconf load / <"$path"
-
+    
     d_conf_paths=()
     for f in "$config_dir/dconf.d"/*; do
         if [ -f "$f" ]; then
             d_conf_paths+=("$f")
-        fi;
+        fi
     done
-
+    
     for d_conf_path in "${d_conf_paths[@]}"; do
-        dconf load "$(echo "/$(basename "$d_conf_path" | tr "." "/" )/")" <"$d_conf_path"
+        dconf load "$(echo "/$(basename "$d_conf_path" | tr "." "/")/")" <"$d_conf_path"
     done
-
+    
     extension_conf_paths=()
     for f in "$extensions_dir"/*; do
         if [ -f "$f" ]; then
             extension_conf_paths+=("$f")
-        fi;
+        fi
     done
-
+    
     for extension in "${extension_conf_paths[@]}"; do
         dconf load "/org/gnome/shell/extensions/$(basename $extension)/" <"$extension"
     done
 }
 
+
+# # Function to export extension settings
+# export_extension_settings() {
+#     dconf dump "/org/gnome/shell/extensions/$1/" >"$extensions_dir/$1"
+# }
+
 dump_settings() {
-    extensions=($(/usr/bin/ls -1 $extensions_dir))
-    for extension in "${extensions[@]}"; do
-        export_extension_settings "$extension"
+    # extensions=($(/usr/bin/ls -1 $extensions_dir))
+    # for extension in "${extensions[@]}"; do
+    # export_extension_settings "$extension"
+    # done
+    
+    d_conf_paths=()
+    for f in "$config_dir/dconf.d"/*; do
+        if [ -f "$f" ]; then
+            d_conf_paths+=("$f")
+        fi
+    done
+    
+    for d_conf_path in "${d_conf_paths[@]}"; do
+        dconf dump "$(echo "/$(basename "$d_conf_path" | tr "." "/")/")" >"$d_conf_path"
+    done
+    
+    extension_conf_paths=()
+    for f in "$extensions_dir"/*; do
+        if [ -f "$f" ]; then
+            extension_conf_paths+=("$f")
+        fi
+    done
+    
+    for extension in "${extension_conf_paths[@]}"; do
+        dconf dump "/org/gnome/shell/extensions/$(basename $extension)/" >"$extension"
     done
 }
 
 # Check for flags
 while [[ $# -gt 0 ]]; do
     case "$1" in
-    --load | -l)
-        load_settings
-        exit 0
+        --load | -l)
+            load_settings
+            exit 0
         ;;
-    --dump | -d)
-        dump_settings
-        exit 0
+        --dump | -d)
+            dump_settings
+            exit 0
         ;;
-    *)
-        echo "Invalid option: $1" >&2
-        exit 1
+        *)
+            echo "Invalid option: $1" >&2
+            exit 1
         ;;
     esac
 done
