Bug fix

diff --git a/.local/bin/gon_backup b/.local/bin/gon_backup
--- a/.local/bin/gon_backup
+++ b/.local/bin/gon_backup
@@ -26,41 +26,43 @@ basic_backup=(
 )
 
 
-ask_delete() {
+# ask_delete() {
     
-    prompt=$(
-		cat <<-EOF
-		Backup interrupted.
-		Would you like delete $backup_dir ? [y/N]:
-		EOF
-    )
+#     prompt=$(
+# 		cat <<-EOF
+# 		Backup interrupted.
+# 		Would you like to delete $backup_dir ? [y/N]:
+# 		EOF
+#     )
     
-    read -rep "$prompt" reply
-    if [[ $reply =~ ^[Yy]$ ]]; then
-        sudo rm -rf "$backup_dir"
-    fi
-}
+#     read -rep "$prompt" reply
+#     if [[ $reply =~ ^[Yy]$ ]]; then
+#         sudo rm -rf "$backup_dir"
+#     fi
+# }
 
 
 filesystem_check(){
-    backup_dir_full="$1"
-    destination="$2"
+    # 'local' must be used
+    local source_dir="$1"
+    local destination="$2"
 
-    backup_dir=$(dirname backup_dir_full)
+    # TODO: Check if destination exists before using dirname?
 
-    if df -P -- "$destination" "$backup_dir" | awk 'NR==2 {dev1=$1} NR==3 {exit($1!=dev1)}'; then
-        echo "$destination and $backup_dir are on the same filesystem"
-        rmdir "$backup_dir_full" 2>/dev/null || echo "$backup_dir is not empty."
+    # Expecting a directory inside an extrenal drive. 
+    # If the destination is "/mnt/drive" the use of "dirname" fails.
+    local destination=$(dirname "$destination")
+
+    if df -P -- "$destination" "$source_dir" | awk 'NR==2 {dev1=$1} NR==3 {exit($1!=dev1)}'; then
+        echo "$destination and $source_dir are on the same filesystem"
+        # rmdir "$source_dir" 2>/dev/null || echo "$source_dir is not empty."
         exit 1
     fi
 }
 
 
 _rsync() {
-    sudo rsync -aAXH --info=progress2 --prune-empty-dirs --delete "$@"
-    [[ $? -eq 0 ]] ||
-    printf "Please check the integrity of the backup," &&
-    read -rp "rsync exited with non-zero return code."
+    sudo rsync -aAXH -h --info=progress2 --prune-empty-dirs --delete $@
 }
 
 
@@ -69,7 +71,7 @@ convertsecs() {
     ((m=(${1}%3600)/60))
     ((s=${1}%60))
     # TODO: move printf
-    printf "Backup completed in %02d:%02d:%02d\n" $h $m $s
+    printf "Backup ended in %02d:%02d:%02d\n" $h $m $s
 }
 
 
@@ -81,43 +83,42 @@ dconf_dump(){
 main() {
 
     # echo "${basic_backup[*]}"
+    local start_="$(date -u +%s)"
+    local start_time=$(date +%F-%T)
+    local destination=/mnt/efd0/gon_backup
 
-    start_time="$(date -u +%s)"
-    start_time_short=$(date +%F-%T)
-    destination=/mnt/efd0/gon_backup
-
-    size="$1"
+    local size="$1"
     case "$size" in
         small)
-            data_source="${basic_backup[*]}"
+            data_sources_list=( "${basic_backup[@]}" )
         ;;
         
         big)
-            data_source="${full_backup[*]}"
+            data_sources_list=( "${basic_backup[@]}" )
         ;;
         
         *)
             printf "Nothing was/will be backed up\n\n"
+            exit
         ;;
     esac
 
-    for dir in "${data_source[@]}"; do
-        filesystem_check $dir $destination
+    for dir in "${data_sources_list[@]}"; do
+        filesystem_check "$dir" "$destination"
     done
 
     printf "%s\nStarting backup to: %s\n\n" "$start_time" "$destination"
+    _rsync ${data_sources_list[@]} "$destination" &&
+    dconf_dump | sudo tee "$destination/dconf" >/dev/null &&
+    sudo btrfs subvolume snapshot "$destination" "${destination}_$start_time"
 
-    _rsync --dry-run "$data_source" "$destination"
-    sudo btrfs subvolume snapshot "$destination" "${destination}_$start_time_short"
-    dconf_dump > "$destination/dconf"
-
-    end_time="$(date -u +%s)"
-    convertsecs $(($end_time-$start_time))
+    end_="$(date -u +%s)"
+    convertsecs $((end_-start_))
 }
 
 
 # INTERRUPTED='False'
 
-trap 'ask_delete; exit 2' INT TERM
+# trap 'ask_delete; exit 2' INT TERM
 
 main "$1"
